PROJECT_REPO='https://github.com/taikedzierski-ldx/mbp-testbed'

library identifier: "commonlib@${BRANCH_NAME}",
    retriever: modernSCM([
      $class: 'GitSCMSource',
      remote: PROJECT_REPO
])

pipeline {
    agent { label "_runner:linux" }

    stages {
        stage("Overall") {
            agent { label "_runner:linux" }

            stages {
                stage("Parallelised") {
                    parallel {
                        stage("Parallel 1") {
                            steps {
                                dir(".") {
                                    tk_say text: "parallel 1", shell: true
                                }
                            }
                        }

                        stage("Parallel 2") {
                            steps {
                                tk_say text: "parallel 2"
                            }
                        }
                    }
                } // stage Clone Repo
            } // inner stages
        } // stage OVerall
    } // stages
} // pipeline
